export const CUSTOMERS = [
  {
    id: 1,
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    id: 2,
    customerName: 'Floyd Miles',
    company: 'Yahoo',
    phoneNumber: '(205) 555-0100',
    email: 'floyd@yahoo.com',
    country: 'Kiribati',
    status: 'Inactive',
  },
  {
    id: 3,
    customerName: 'Ronald Richards',
    company: 'Adobe',
    phoneNumber: '(302) 555-0107',
    email: 'ronald@adobe.com',
    country: 'Israel',
    status: 'Inactive',
  },
  {
    id: 4,
    customerName: 'Marvin McKinney',
    company: 'Tesla',
    phoneNumber: '(252) 555-0126',
    email: 'marvin@tesla.com',
    country: 'Iran',
    status: 'Active',
  },
  {
    id: 5,
    customerName: 'Jerome Bell',
    company: 'Google',
    phoneNumber: '(629) 555-0129',
    email: 'jerome@google.com',
    country: 'Réunion',
    status: 'Active',
  },
  {
    id: 6,
    customerName: 'Kathryn Murphy',
    company: 'Microsoft',
    phoneNumber: '(406) 555-0120',
    email: 'kathryn@microsoft.com',
    country: 'Curaçao',
    status: 'Active',
  },
  {
    id: 7,
    customerName: 'Jacob Jones',
    company: 'Yahoo',
    phoneNumber: '(208) 555-0112',
    email: 'jacob@yahoo.com',
    country: 'Brazil',
    status: 'Active',
  },
  {
    id: 8,
    customerName: 'Kristin Watson',
    company: 'Facebook',
    phoneNumber: '(704) 555-0127',
    email: 'kristin@facebook.com',
    country: 'Åland Islands',
    status: 'Inactive',
  },
  {
    id: 9,
    customerName: 'Adam Smith',
    company: 'Apple',
    phoneNumber: '(123) 555-0101',
    email: 'adam@apple.com',
    country: 'United Kingdom',
    status: 'Active',
  },
  {
    id: 10,
    customerName: 'Emily Taylor',
    company: 'Google',
    phoneNumber: '(234) 555-0102',
    email: 'emily@google.com',
    country: 'United States',
    status: 'Active',
  },
  {
    id: 11,
    customerName: 'Michael Johnson',
    company: 'Amazon',
    phoneNumber: '(345) 555-0103',
    email: 'michael@amazon.com',
    country: 'Canada',
    status: 'Active',
  },
  {
    id: 12,
    customerName: 'Sophia Martinez',
    company: 'Microsoft',
    phoneNumber: '(456) 555-0104',
    email: 'sophia@microsoft.com',
    country: 'Mexico',
    status: 'Active',
  },
  {
    id: 13,
    customerName: 'Daniel Garcia',
    company: 'Tesla',
    phoneNumber: '(567) 555-0105',
    email: 'daniel@tesla.com',
    country: 'France',
    status: 'Active',
  },
  {
    id: 14,
    customerName: 'Emma Hernandez',
    company: 'Facebook',
    phoneNumber: '(678) 555-0106',
    email: 'emma@facebook.com',
    country: 'Germany',
    status: 'Active',
  },
  {
    id: 15,
    customerName: 'Matthew Lopez',
    company: 'Apple',
    phoneNumber: '(789) 555-0107',
    email: 'matthew@apple.com',
    country: 'Japan',
    status: 'Active',
  },
  {
    id: 16,
    customerName: 'Olivia Gonzalez',
    company: 'Google',
    phoneNumber: '(890) 555-0108',
    email: 'olivia@google.com',
    country: 'Australia',
    status: 'Active',
  },
  {
    id: 17,
    customerName: 'Ethan Wilson',
    company: 'Microsoft',
    phoneNumber: '(901) 555-0109',
    email: 'ethan@microsoft.com',
    country: 'China',
    status: 'Active',
  },
  {
    id: 18,
    customerName: 'Ava Anderson',
    company: 'Amazon',
    phoneNumber: '(012) 555-0110',
    email: 'ava@amazon.com',
    country: 'South Korea',
    status: 'Active',
  },
  {
    id: 19,
    customerName: 'John Doe',
    company: 'Google',
    phoneNumber: '(012) 555-0121',
    email: 'john@google.com',
    country: 'Germany',
    status: 'Active',
  },
  {
    id: 20,
    customerName: 'Jane Smith',
    company: 'Apple',
    phoneNumber: '(012) 555-0122',
    email: 'jane@apple.com',
    country: 'France',
    status: 'Inactive',
  },
  {
    id: 21,
    customerName: 'Michael Johnson',
    company: 'Microsoft',
    phoneNumber: '(012) 555-0123',
    email: 'michael@microsoft.com',
    country: 'Spain',
    status: 'Active',
  },
  {
    id: 22,
    customerName: 'Emma Brown',
    company: 'Facebook',
    phoneNumber: '(012) 555-0124',
    email: 'emma@facebook.com',
    country: 'Italy',
    status: 'Inactive',
  },
  {
    id: 23,
    customerName: 'James Wilson',
    company: 'Netflix',
    phoneNumber: '(012) 555-0125',
    email: 'james@netflix.com',
    country: 'Canada',
    status: 'Active',
  },
  {
    id: 24,
    customerName: 'Olivia Martinez',
    company: 'Tesla',
    phoneNumber: '(012) 555-0126',
    email: 'olivia@tesla.com',
    country: 'Australia',
    status: 'Inactive',
  },
];
